"""add slot telemetry columns

Revision ID: 5b77a1c3f39e
Revises: fe131c9325a0
Create Date: 2026-02-27 17:41:31.599215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b77a1c3f39e'
down_revision: Union[str, None] = 'fe131c9325a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_telemetry', sa.Column('intended_slot_plan_json', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('run_telemetry', sa.Column('slot_mismatch_json', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_telemetry', 'slot_mismatch_json')
    op.drop_column('run_telemetry', 'intended_slot_plan_json')
    # ### end Alembic commands ###
