"""initial schema

Revision ID: fe131c9325a0
Revises: 
Create Date: 2026-02-27 14:18:22.777535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe131c9325a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('telemetry_enabled', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('render_settings', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_qc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('role_guess', sa.Enum('human_identity', 'object_fidelity', 'environment_plate', 'style_look', 'composition_pose', 'texture_material', 'mixed', name='role_guess_enum'), nullable=True),
    sa.Column('role_confidence', sa.Float(), nullable=True),
    sa.Column('ambiguity_score', sa.Float(), nullable=True),
    sa.Column('quality_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('face_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('environment_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('lighting_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('style_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_qc_asset_id'), 'asset_qc', ['asset_id'], unique=True)
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('upload_plan', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_experiment_id'), 'conditions', ['experiment_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('repeat_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='run_status_enum'), nullable=False),
    sa.Column('output_image_path', sa.String(length=500), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_condition_id'), 'runs', ['condition_id'], unique=False)
    op.create_table('run_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('thought_summary_raw', sa.Text(), nullable=True),
    sa.Column('thought_signature', sa.String(length=255), nullable=True),
    sa.Column('usage_metadata_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('safety_metadata_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('thinking_level', sa.String(length=50), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('allocation_report_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('allocation_parse_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_telemetry_run_id'), 'run_telemetry', ['run_id'], unique=True)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('identity_score', sa.Integer(), nullable=False),
    sa.Column('object_score', sa.Integer(), nullable=False),
    sa.Column('style_score', sa.Integer(), nullable=False),
    sa.Column('environment_score', sa.Integer(), nullable=False),
    sa.Column('hallucination', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_run_id'), 'scores', ['run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_run_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_run_telemetry_run_id'), table_name='run_telemetry')
    op.drop_table('run_telemetry')
    op.drop_index(op.f('ix_runs_condition_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_conditions_experiment_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_asset_qc_asset_id'), table_name='asset_qc')
    op.drop_table('asset_qc')
    op.drop_table('experiments')
    op.drop_table('assets')
    # ### end Alembic commands ###
